### ISSUE TITLE
Max Planck School of Cognition Workshop

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/datalad-course#1]
@mih and I will be going to Dresden to teach a 2-half day DataLad workshop.

Important infos at a glance: 
- Slides are created in this repo, branch ``ws-mpsc``
- Audience response system (for MC questions or polls) at https://www.directpoll.com/c?XDVhEt8n6fLejElM1ruTg4PqVxQiKbA
- Zenodo deposition for slides will be at https://zenodo.org/deposit/6827086
- Attendee information is at https://docs.google.com/forms/d/e/1FAIpQLSd3V1v4gy0jXbpc58s7VttuJO3Fr4wOJRr8Tl2LLy7wWDJpVw/viewform
    - barely anyone used datalad
    - 2/3 used Git
    - of those that used Git, less than half did so collaboratively
    - 50% did not share code or data yet, 35% shared both code and data already

TODOs:
- [x] fine-tune content and exercises
    - [x] @mih adds "Demo of core features" to the slides at ``mpsc-introduction.html`` 
    - [x] @mih adds "Collaboration" part to the slides at ``mpsc-datapublication.html``
    - [x] datalad ML example tested
    - [x] datalad create-sibling-osf example tested
    - [x] datalad create-sibling-gin example tested
    - [x] datalad create-sibling-webdav example tested
    - [x] @mih completes block 2 start exercises
    - [x] @mih contributes "outro" slides
    - [x] @mih core feature set demo compiled and tested. We will use http://handbook.datalad.org/en/latest/code_from_chapters/yale.html#using-published-datasets and prepend the final `rerun` with a `drop` of the brainmask, a failing `get`, and a parameter-less `rerun`, which will bring the file back, albeit in a different version. We can remove the compression in the script to make it reproducible (and show that).
    - [x] @mih release datalad-next with `configuration` update
- [x] get train tickets
- [x] Set up a Jupyterhub, map to datalad-hub.inm7.de
- [x] Create around 20 user accounts; we don't have participant names, we can use random words, print them out, and hand them to people as their username
- [x] Bring a stash of post-its for participants to indicate support requsts
- [x] include some charts from attendee survey (e.g., Git usage) into the slides
- [x] Deposit PDFs of slides on Zenodo and publish the draft
- [x] Render slower version of webdav walk-through and post on youtube

**Comment by mih** [comment]
Tentative schedule (subject to further discussion and changes)

# Dresden Workshop
## Block 1 (90 min)

- House-keeping (10 min)
- L: DataLad in the wild Conceptual Intro (15 min) [@adswa]
- P: Hands-on Terminal and general git/git-annex/datalad usage; where to get help (30 min) [@adswa]
- L: Demo "core API" (create, save, status, diff, run) (30 min) [@mih]

## Block 2 (120 min)

- P: Example RDM task solution attempt (30 min) [@mih]

  - Create a dataset, add a file, save the dataset with a commit message
  - Download a a file from the web with prov-capture
  - Copy a file in a dataset (without saving it), look at the difference
    between particular states of the dataset

- L: Code-along basics (90 min) [@adswa]

## Day 2 Block 3 (90 min)

- L: Collaboration: How does it work, what infrastructures can I use? (30 min) [@adswa]

  - OSF
  - WebDAV
  - GIN

- P: Live collaboration event (60 min) [backdrop slide @mih]

## Day 2 Block 4 (90 min)

- L: Computational reproducibility (60 min) [@adswa]

  - DVC demo
  - Container

- L: Outro (20 min) [@mih "what is datalad?"]

  - Demo slide: FAIRly big recompute
  - Data portability, aid moving to next job/institution

- Q&A (15 min)

**Comment by adswa** [comment]
Slides are at https://zenodo.org/record/6827086

**Comment by adswa** [comment]
Done, worked very well and smoothly
